satnogs-rotator-firmware: easycomm Class Reference
easycomm Class Reference
Class that functions for easycomm 3 implementation.
#include <easycomm.h>
Public Member Functions
void easycomm_init ()
Initialize the RS485 bus.
void easycomm_proc ()
Get the commands from RS485 and response to the client.
Private Member Functions
bool isNumber (char *input)
Detailed Description
Class that functions for easycomm 3 implementation.
Definition at line 31 of file easycomm.h.
Member Function Documentation
easycomm_init()
void easycomm::easycomm_init () inline
Initialize the RS485 bus.
Definition at line 39 of file easycomm.h.
References BAUDRATE, and rs485::begin().
Referenced by setup().
easycomm_proc()
void easycomm::easycomm_proc () inline
Get the commands from RS485 and response to the client.
Definition at line 48 of file easycomm.h.
References rs485::available(), BUFFER_SIZE, control_az, control_el, _rotator::control_mode, _control::d, rs485::flush(), _rotator::homing_flag, _control::i, _control::input, _rotator::inside_temperature, isNumber(), _control::load, _control::p, _rotator::park_az, _rotator::park_el, position, rs485::print(), rs485::read(), rotator, _rotator::rotator_error, _rotator::rotator_status, _control::setpoint, _control::setpoint_speed, speed, _control::speed, _rotator::switch_az, and _rotator::switch_el.
Referenced by loop().
isNumber()
bool easycomm::isNumber (char * input) inline private
Definition at line 378 of file easycomm.h.
Referenced by easycomm_proc().
The documentation for this class was generated from the following file:
libraries/easycomm.h