satnogs-rotator-firmware: rs485 Class Reference
rs485 Class Reference
Class that functions for interacting with a RS485 transceiver.
#include <rs485.h>
Public Member Functions
rs485 (uint8_t pin_dir, uint16_t tx_time)
void begin (uint16_t baudrate)
Initialize the RS485 transceiver.
void print (String str)
Print a string to RS485 bus.
uint8_t read ()
Read a char/uint8_t from RS485 bus.
uint8_t available (void)
The number of chars/uint8_t that are available in RS485 buffer.
void flush ()
Waits for the transmission of outgoing serial data to complete.
void end ()
Disables RS485 communication.
Private Attributes
uint8_t _pin_dir
uint16_t _tx_time
Detailed Description
Class that functions for interacting with a RS485 transceiver.
Parameters
pin_dir Digital pin, to set read or write to RS485 bus
tx_time Time delay in ms in order to transmit and change the status of direction pin
Definition at line 23 of file rs485.h.
Constructor & Destructor Documentation
rs485()
rs485::rs485 (uint8_t pin_dir, uint16_t tx_time) inline
Definition at line 26 of file rs485.h.
References _pin_dir, and _tx_time.
Member Function Documentation
available()
uint8_t rs485::available (void) inline
The number of chars/uint8_t that are available in RS485 buffer.
Returns
A char/uint8_t
Definition at line 73 of file rs485.h.
Referenced by easycomm::easycomm_proc(), and ISR().
begin()
void rs485::begin (uint16_t baudrate) inline
Initialize the RS485 transceiver.
Parameters
baudrate Set the baudrate of RS485 bus
Definition at line 38 of file rs485.h.
References _pin_dir.
Referenced by easycomm::easycomm_init().
end()
void rs485::end () inline
Disables RS485 communication.
Definition at line 91 of file rs485.h.
flush()
void rs485::flush () inline
Waits for the transmission of outgoing serial data to complete.
Definition at line 82 of file rs485.h.
Referenced by easycomm::easycomm_proc(), and ISR().
print()
void rs485::print (String str) inline
Print a string to RS485 bus.
Parameters
str A String to transmit
Definition at line 50 of file rs485.h.
References _pin_dir, and _tx_time.
Referenced by easycomm::easycomm_proc(), and ISR().
read()
uint8_t rs485::read () inline
Read a char/uint8_t from RS485 bus.
Returns
A char/uint8_t
Definition at line 63 of file rs485.h.
Referenced by easycomm::easycomm_proc(), and ISR().
Member Data Documentation
_pin_dir
uint8_t rs485::_pin_dir private
Definition at line 96 of file rs485.h.
Referenced by begin(), print(), and rs485().
_tx_time
uint16_t rs485::_tx_time private
Definition at line 97 of file rs485.h.
Referenced by print(), and rs485().
The documentation for this class was generated from the following file:
libraries/rs485.h