satnogs-rotator-firmware: libraries/watchdog.h File Reference
watchdog.h File Reference
#include <avr/wdt.h>
#include "globals.h"
#include "easycomm.h"
#include "rotator_pins.h"
Classes
class wdt_timer
Class that functions for interacting with a watchdog timer.
Functions
ISR (WDT_vect)
Watchdog timer interrupt routine that implements a minimal easycomm protocol to get the errors and reset the uC.
Detailed Description
It is a driver for watchdog timer.
Licensed under the GPLv3
Definition in file watchdog.h.
Function Documentation
ISR()
ISR (WDT_vect)
Watchdog timer interrupt routine that implements a minimal easycomm protocol to get the errors and reset the uC.
Definition at line 56 of file watchdog.h.
References rs485::available(), BUFFER_SIZE, error, rs485::flush(), MOTOR_EN, rs485::print(), rs485::read(), rotator, _rotator::rotator_error, _rotator::rotator_status, and wdt_error.